#!/usr/bin/python3
# encoding=UTF-8

# Copyright © 2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import argparse
import base64
import hashlib
import hmac
import struct
import sys
import time

lambda: (yield from 0)  # Python >= 3.3 is required

default_len = 6

def hotp(*, key, n, len=default_len, dgst=hashlib.sha1):
    # RFC 4226
    msg = struct.pack('>Q', n)
    mac = hmac.HMAC(key=key, msg=msg, digestmod=dgst)
    mac = mac.digest()
    offset = mac[-1] & 0xF
    code = mac[offset:(offset + 4)]
    [code] = struct.unpack('>I', code)
    code = code & ~(1 << 31)
    code = str(code)[-len:]
    return code

def totp(*, key, len=default_len, dgst=hashlib.sha1, step=30):
    # RFC 6238
    t = int(time.time()) // step
    return hotp(key=key, n=t, len=len, dgst=dgst)

def main():
    ap = argparse.ArgumentParser()
    ap.set_defaults(len=default_len)
    for i in (6, 7, 8):
        msg = 'print {0} digits'.format(i)
        if i == default_len:
            msg += ' (default)'
        ap.add_argument('-{0}'.format(i), dest='len', action='store_const', const=i, help=msg)
    opts = ap.parse_args();
    key = sys.stdin.read().strip().upper()
    key = base64.b32decode(key)
    code = totp(key=key, len=opts.len)
    print(code)

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
