#!/usr/bin/python3
# encoding=UTF-8

# Copyright © 2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

'''
utotp reads base32-encoded secret key from stdin
and generates a time-based one-time password
(as per RFC 6238).
'''

import argparse
import base64
import binascii
import hashlib
import hmac
import struct
import sys
import time

lambda: (yield from 0)  # Python >= 3.3 is required

default_len = 6
default_dgst = hashlib.sha1

def hotp(*, key, n, len=default_len, dgst=default_dgst):
    # RFC 4226
    msg = struct.pack('>Q', n)
    mac = hmac.HMAC(key=key, msg=msg, digestmod=dgst)
    mac = mac.digest()
    offset = mac[-1] & 0xF
    code = mac[offset:(offset + 4)]
    [code] = struct.unpack('>I', code)
    code = code & ~(1 << 31)
    code = '{0:0{len}}'.format(code, len=len)
    code = code[-len:]
    return code

def totp(*, key, len=default_len, dgst=default_dgst, step=30):
    # RFC 6238
    t = int(time.time()) // step
    return hotp(key=key, n=t, len=len, dgst=dgst)

def b32decode(s):
    s = s.strip()
    s = s.upper()
    modlen = len(s) % 8
    if modlen > 0:
        s += '=' * (8 - modlen)
    assert len(s) % 8 == 0
    return base64.b32decode(s)

def main():
    descr = (__doc__ or '').strip()
    ap = argparse.ArgumentParser(description=descr)
    ag = ap.add_mutually_exclusive_group()
    for i in (6, 7, 8):
        msg = 'print {0} digits'.format(i)
        if i == default_len:
            msg += ' (default)'
            ap.set_defaults(len=i)
        ag.add_argument('-{0}'.format(i), dest='len', action='store_const', const=i, help=msg)
    ag = ap.add_mutually_exclusive_group()
    for i in (1, 256, 512):
        dgst = getattr(hashlib, 'sha{0}'.format(i))
        msg = 'use HMAC-SHA-{0}'.format(i)
        if dgst is default_dgst:
            msg += ' (default)'
            ap.set_defaults(dgst=dgst)
        ag.add_argument('--sha{0}'.format(i), dest='dgst', action='store_const', const=dgst, help=msg)
    opts = ap.parse_args();
    key = sys.stdin.read()
    try:
        key = b32decode(key)
    except binascii.Error:
        print('{prog}: secret key cannot be base32-decoded'.format(prog=ap.prog), file=sys.stderr)
        sys.exit(1)
    code = totp(key=key, len=opts.len, dgst=opts.dgst)
    print(code)

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
